export enum MessageSource {
  EXTENSION = "chatterpack:extension",
  SITE = "chatterpack:site",
}

export enum MessageType {
  WS_CHAT = "WS_CHAT",
  CHAT_MESSAGE = "CHAT_MESSAGE",
  CHAT_CONRROLLER = "CHAT_CONRROLLER",
  COMMAND_NOT_FOUND = "COMMAND_NOT_FOUND",
}

export enum RuntimeMessageType {
  GO_TO_TAB = "GO_TO_TAB",
  GET_ACTIVE_COMMANDS = "GET_ACTIVE_COMMANDS",
  GET_ACTIVE_MODERATION_RULES = "GET_ACTIVE_MODERATION_RULES",
  GET_ACTIVE_HIGHLIGHTS = "GET_ACTIVE_HIGHLIGHTS",
  SYNC_MODERATION_RULES = "SYNC_MODERATION_RULES",
  SYNC_HIGHLIGHTS = "SYNC_HIGHLIGHTS",
  SYNC_COMMANDS = "SYNC_COMMANDS",
}
